name: Node CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies & test
        run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
